name: Release Workflow

on:
  push:
    branches:
      - main  # Adjust this to your default branch
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run yarn release
        run: yarn release

      - name: Upload release files
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PAT_TOKEN }}
          file_glob: true
          file: releases/*  # Adjust the path to your release files
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"  # Customize the release description
